FROM oven/bun:1.1.7-alpine AS builder

WORKDIR /app

COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile || true

COPY . .

FROM oven/bun:1.1.7-alpine

RUN addgroup -S crocoder \
      && adduser -S crocoder -G crocoder

WORKDIR /app

COPY --chown=crocoder:crocoder --from=builder /app/node_modules ./node_modules
COPY --chown=crocoder:crocoder --from=builder /app/index.ts ./
COPY --chown=crocoder:crocoder --from=builder /app/package.json ./
COPY --chown=crocoder:crocoder --from=builder /app/bun.lockb ./bun.lockb

USER crocoder

EXPOSE 3000

CMD ["bun", "run", "index.ts"]
