FROM oven/bun:1.1.7-alpine AS builder

WORKDIR /app

COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile || true

COPY . .

FROM oven/bun:1.1.7-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/index.ts ./
COPY --from=builder /app/package.json ./
COPY --from=builder /app/bun.lockb ./bun.lockb

EXPOSE 3000

CMD ["bun", "run", "index.ts"]
